version: '3.2'
services:
  master-db-dev:
    image: postgres:15.3-alpine
    container_name: master-db-dev
    networks:
      - default
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      #- ./my_db_scripts:/docker-entrypoint-initdb.d:ro
    env_file:
      - environment/dev.env
    restart: unless-stopped
    healthcheck:
      test: "exit 0"


  # master-es-dev:
  #   container_name: master-es-dev
  #   image: elasticsearch:7.17.10
  #   environment:
  #     - discovery.type=single-node
  #     # - xpack.security.enabled=false
  #     - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
  #   volumes:
  #     - ./hunspell:/usr/share/elasticsearch/config/hunspell:ro
  #     # - ./es_data:/usr/share/elasticsearch/data:rw
  #   # ports:
  #   #   - "9500:9200"
  #   networks:
  #     - default
  #   healthcheck:
  #     test: "exit 0"

  master-app-dev:
    build: .
    container_name: master-app-dev
    entrypoint: /entrypoint.sh
    networks:
      - default
      # - proxy
    working_dir: /app
    ports:
      - "8001:80"
      # - "9500"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app:rw
        #- /etc/hosts:/etc/hosts:ro
    env_file:
      - environment/dev.env
    command: python manage.py runserver 0.0.0.0:80
    restart: unless-stopped
    depends_on:
      master-db-dev:
        condition: service_healthy
      # master-es-dev:
      #   condition: service_healthy
      # - master-solr-dev

  # master-solr-dev:
  #   container_name: master-solr-dev
  #   image: solr:6.6.6
  #   # environment:
  #     # - discovery.type=single-node
  #     # - xpack.security.enabled=false
  #   # volumes:
  #   #   - ./hunspell:/usr/share/elasticsearch/config/hunspell:ro
  #   ports:
  #     - "8983:8983"
  #   networks:
  #     - default
  #   command: #/opt/solr/bin/solr create -c tester -n basic_config
  #     - solr-precreate
  #     - tester

networks:
  # proxy:
  #   name: 'proxy'
  #   external: true
  default:
    name: master-dev
