# Generated by Django 4.2.9 on 2024-02-04 15:12

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('logo', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'вид деятельности',
                'verbose_name_plural': 'виды деятельности',
            },
        ),
        migrations.CreateModel(
            name='ActivityPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('layout', models.CharField(choices=[('blocks', 'Блоки (без лого)'), ('image-blocks', 'Блоки с логотипом на фоне')], default='blocks', max_length=32, verbose_name='Макет')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CategoryOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('name', models.CharField(max_length=128, verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'вид организаций',
                'verbose_name_plural': 'виды организаций',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
                ('schedule', models.CharField(blank=True, max_length=256, null=True, verbose_name='Режим работы')),
                ('address_same', models.BooleanField(default=True, verbose_name='Адрес совпадает с адресом организации')),
                ('address', models.CharField(blank=True, help_text='Заполняется если адрес секции не совпадает с адресом организации', max_length=512, null=True, verbose_name='Адрес')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Описание')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.activity', verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'секция',
                'verbose_name_plural': 'секции',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('level', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('list_order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(max_length=256, verbose_name='Полное название')),
                ('short_name', models.CharField(max_length=128, verbose_name='Краткое название')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес')),
                ('fax', models.CharField(blank=True, max_length=32, null=True, verbose_name='Факс приемной')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('shedule', models.CharField(blank=True, max_length=256, null=True, verbose_name='График работы')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон приемной')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.categoryorganization', verbose_name='Вид организации (не обязательно)')),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Логотип')),
                ('page', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page', verbose_name='Ссылка на страницу')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.organization', verbose_name='Родительская организация')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
                'ordering': ['list_order'],
            },
        ),
        migrations.CreateModel(
            name='Otdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.organization', verbose_name='Организация')),
                ('page', cms.models.fields.PageField(blank=True, help_text='Не обязательно', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page', verbose_name='Ссылка на страницу')),
            ],
            options={
                'verbose_name': 'отдел',
                'verbose_name_plural': 'отделы',
                'ordering': ['organization', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SotrudnikOrganizationPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('apparat', models.BooleanField(default=False, help_text='Оставить только сотрудников аппарата (поле "Отдел" будет проигнорировано)', verbose_name='Только аппарат управления')),
                ('layout', models.CharField(choices=[('rows', 'Построчно'), ('blocks', 'Блоки')], default='rows', max_length=32, verbose_name='Макет')),
                ('show_detail_link', models.BooleanField(default=True, help_text='если она есть', verbose_name='Отображать ссылку на страницу сотрудников')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.organization', verbose_name='Организация')),
                ('otdel', models.ForeignKey(blank=True, help_text='Если не заполнено, сотрудник будет                                 отображаться в разделе "Прочие сотрудники" организации', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.otdel', verbose_name='Отдел')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Sotrudnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('lastname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Отчество')),
                ('position', models.CharField(max_length=128, verbose_name='Должность')),
                ('apparat', models.BooleanField(default=False, help_text='Если отмечено, сотрудник будет выведен                                   в разделе "Аппарат управления" организации', verbose_name='В аппарате управления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.organization', verbose_name='Организация')),
                ('otdel', models.ForeignKey(blank=True, help_text='Если не заполнено, сотрудник будет                                 отображаться в разделе "Прочие сотрудники" организации', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.otdel', verbose_name='Отдел')),
                ('page', cms.models.fields.PageField(blank=True, help_text='Не обязательно', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page', verbose_name='Ссылка на страницу')),
                ('photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['organization', 'otdel', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PhotoDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.department')),
                ('photo', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер')),
                ('otdel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.otdel')),
                ('sotrudnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.sotrudnik')),
            ],
            options={
                'verbose_name': 'телефон',
                'verbose_name_plural': 'телефоны',
            },
        ),
        migrations.CreateModel(
            name='OtdelOrganizationPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('show_detail_link', models.BooleanField(default=True, help_text='если она есть', verbose_name='Отображать ссылку на страницы отделов и сотрудников')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.organization', verbose_name='Организация')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='LogoPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.organization', verbose_name='Организация')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DepartmentPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.activity', verbose_name='Вид спорта')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='AttributesPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.organization', verbose_name='Организация')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
