# Generated by Django 4.2.9 on 2024-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_sotrudnik_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='otdelorganizationplugin',
            name='expand_all',
            field=models.BooleanField(default=True, verbose_name='Развернуть все отделы'),
        ),
    ]
