# Generated by Django 4.2.9 on 2024-03-29 04:52

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('djangocms_animated_numbers', '0007_animatednumbers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animatednumbers',
            name='image',
        ),
        migrations.AddField(
            model_name='number',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='120x120', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Картинка'),
        ),
    ]
