# Generated by Django 4.2.9 on 2024-04-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoblock', '0008_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoblock',
            name='height',
        ),
        migrations.AddField(
            model_name='infoblock',
            name='num_items',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество отображаемых элементов'),
        ),
    ]
