# Generated by Django 4.2.9 on 2024-02-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='value',
            field=models.CharField(default='', max_length=64, verbose_name='Стоимость'),
        ),
    ]
