# Generated by Django 4.2.9 on 2024-03-22 07:17

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('prices', '0002_price_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='prices', to='cms.placeholder'),
        ),
    ]
