# Generated by Django 4.2.9 on 2024-03-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_price_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='placeholder',
        ),
    ]
