# Generated by Django 4.2.9 on 2024-03-23 09:40

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('prices', '0007_alter_price_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='content', to='cms.placeholder'),
        ),
    ]
