# Generated by Django 4.2.9 on 2025-01-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_created_at_review_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
