# Generated by Django 4.2.9 on 2024-02-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_schedule_alter_sitesettings_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='menu_style',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='share_fb',
            field=models.BooleanField(default=False, verbose_name='Share Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='share_ok',
            field=models.BooleanField(default=True, verbose_name='Share Одноклассники'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='share_twitter',
            field=models.BooleanField(default=False, verbose_name='Share Twitter'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='share_vk',
            field=models.BooleanField(default=True, verbose_name='Share Вконтакте'),
        ),
    ]
