# Generated by Django 4.2.9 on 2024-02-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sitesettings_menu_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerplugin',
            name='subtitle_position',
            field=models.CharField(choices=[('bottom', 'Под заголовком'), ('top', 'Над заголовком')], default='bottom', max_length=32, verbose_name='Позиция подзаголовка'),
        ),
    ]
