# Generated by Django 4.2.9 on 2024-03-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_headerplugin_subtitle_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accordionplugin',
            name='auto_open',
        ),
        migrations.RemoveField(
            model_name='accordionplugin',
            name='speed',
        ),
        migrations.AddField(
            model_name='accordionplugin',
            name='open_all',
            field=models.BooleanField(default=True, help_text='Если активно, номер открытой вкладки будет проигнорирован', verbose_name='Все вкладки развернуты при загрузке'),
        ),
        migrations.AlterField(
            model_name='accordionplugin',
            name='close_others',
            field=models.BooleanField(default=True, verbose_name='Клик по элементу будет закрывать другие вкладки'),
        ),
        migrations.AlterField(
            model_name='accordionplugin',
            name='num_auto_open',
            field=models.PositiveSmallIntegerField(default=1, help_text='если 0 - все вкладки будут закрыты', verbose_name='Номер открытой вкладки при загрузке'),
        ),
    ]
