# Generated by Django 4.2.9 on 2024-03-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_accordionplugin_auto_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordionplugin',
            name='open_all',
            field=models.BooleanField(default=False, help_text='Если активно, номер открытой вкладки будет проигнорирован', verbose_name='Все вкладки развернуты при загрузке'),
        ),
    ]
