# Generated by Django 4.2.9 on 2024-03-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_accordionplugin_open_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabplugin',
            name='num_auto_open',
            field=models.PositiveSmallIntegerField(default=1, help_text='если 0 - все вкладки будут закрыты', verbose_name='Номер открытой вкладки'),
        ),
        migrations.AlterField(
            model_name='accordionplugin',
            name='num_auto_open',
            field=models.PositiveSmallIntegerField(default=1, help_text='если 0 - все вкладки будут закрыты', verbose_name='Номер открытой вкладки'),
        ),
    ]
