# Generated by Django 4.2.9 on 2024-03-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tabplugin_num_auto_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabplugin',
            name='num_auto_open',
        ),
        migrations.AddField(
            model_name='tabsplugin',
            name='num_auto_open',
            field=models.PositiveSmallIntegerField(default=1, help_text='если 0 - все вкладки будут закрыты', verbose_name='Номер открытой вкладки'),
        ),
    ]
