# Generated by Django 4.2.9 on 2024-03-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_tabplugin_num_auto_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accordionplugin',
            name='hide_borders',
            field=models.BooleanField(default=False, verbose_name='Скрыть линии границ аккордеона'),
        ),
    ]
