# Generated by Django 4.2.9 on 2024-04-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_accordionplugin_hide_borders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemaccordionplugin',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Название'),
        ),
    ]
