# Generated by Django 4.2.9 on 2024-04-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_itemaccordionplugin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accordionplugin',
            name='css_classes',
            field=models.CharField(blank=True, default='', help_text='Bootstrap 5', max_length=256, null=True, verbose_name='CSS классы'),
        ),
        migrations.AddField(
            model_name='itemaccordionplugin',
            name='css_classes',
            field=models.CharField(blank=True, default='', help_text='Bootstrap 5', max_length=256, null=True, verbose_name='CSS классы'),
        ),
    ]
